# Generated by Django 3.0.3 on 2020-02-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
