# Generated by Django 3.0.3 on 2020-02-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_announce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
